apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-csi-auth
  labels:
    app: nginx-csi-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-csi-auth
  template:
    metadata:
      labels:
        app: nginx-csi-auth
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: pvc-csi-auth
