kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc-csi-noauth
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
    storageClassName: csi-noauth
