kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc-intree-auth
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
    storageClassName: intree-auth
