kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc-intree-noauth
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
    storageClassName: intree-noauth
