kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc-csi-auth
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
    storageClassName: csi-auth
