name: pxc config credentials
synopsis: Setup pxc authentication
options:
- name: help
  shorthand: h
  default_value: "false"
  usage: help for credentials
inherited_options:
- name: pxc.config
  usage: Config file (default is $HOME/.pxc/config.yml)
- name: pxc.config-dir
  default_value: /home/lpabon/.pxc
  usage: Config directory
- name: pxc.context
  usage: Force context name for the command
- name: pxc.token
  usage: Portworx authentication token
- name: pxc.v
  default_value: "0"
  usage: '[0-3] Log level verbosity'
see_also:
- pxc config - Setup pxc configuration
- delete - Delete pxc authentication information
- set - Set authentication information for Portworx cluster
- whoami - Shows current authentication information
