name: pxc config context use
synopsis: Sets the context to use
options:
- name: help
  shorthand: h
  default_value: "false"
  usage: help for use
- name: name
  usage: Name of context
inherited_options:
- name: pxc.config
  usage: Config file (default is $HOME/.pxc/config.yml)
- name: pxc.config-dir
  default_value: /home/lpabon/.pxc
  usage: Config directory
- name: pxc.context
  usage: Force context name for the command
- name: pxc.token
  usage: Portworx authentication token
- name: pxc.v
  default_value: "0"
  usage: '[0-3] Log level verbosity'
see_also:
- pxc config context - Setup pxc contexts
