name: pxc config context set
synopsis: |
  Set context information for which cluster and credentials to uset
options:
- name: cluster
  usage: Name of cluster information
- name: credentials
  usage: Name of credentials
- name: help
  shorthand: h
  default_value: "false"
  usage: help for set
- name: name
  usage: Name of context
inherited_options:
- name: pxc.config
  usage: Config file (default is $HOME/.pxc/config.yml)
- name: pxc.config-dir
  default_value: /home/lpabon/.pxc
  usage: Config directory
- name: pxc.context
  usage: Force context name for the command
- name: pxc.token
  usage: Portworx authentication token
- name: pxc.v
  default_value: "0"
  usage: '[0-3] Log level verbosity'
example: |2-

    # Login to portworx using a secret in Kubernetes
    pxc config context set --credentials=mycreds --cluster=mycluster
see_also:
- pxc config context - Setup pxc contexts
