name: pxc config cluster set
synopsis: Configure pxc to communicate with your cluster
options:
- name: cafile
  usage: Path to CA certificate
- name: endpoint
  usage: |
    Direct connection to a Portworx node gRPC endpoint. This endpoint would be used instead of the Kubernetes Portworx API service. Example: 1.1.1.1:9020
- name: help
  shorthand: h
  default_value: "false"
  usage: help for set
- name: name
  usage: |
    Name for Portworx cluster (ignored when used as a kubectl plugin)
- name: tls
  default_value: "false"
  usage: |
    Enable if using TLS. Passing a CA will enable this automatically.
inherited_options:
- name: pxc.config
  usage: Config file (default is $HOME/.pxc/config.yml)
- name: pxc.config-dir
  default_value: /home/lpabon/.pxc
  usage: Config directory
- name: pxc.context
  usage: Force context name for the command
- name: pxc.token
  usage: Portworx authentication token
- name: pxc.v
  default_value: "0"
  usage: '[0-3] Log level verbosity'
example: |2-

    # Setup simple endpoint
    pxc config cluster set --name=mycluster --endpoint=127.0.0.1:9020

    # If in kubectl plugin mode
    pxc config cluster set --portworx-service-port=8900
see_also:
- pxc config cluster - Setup pxc cluster configuration
