name: pxc config credentials set
synopsis: Set authentication information for Portworx cluster
description: |-
  Saves your Portworx authentication information for the current
  user in the kubeconfig file. This will enable pxc to fetch the authentication
  information from the config file without having the user provide it each time.
options:
- name: auth-token
  usage: Authentication token
- name: help
  shorthand: h
  default_value: "false"
  usage: help for set
- name: k8s-secret-name
  usage: Kubernetes secret name with the auth token
- name: k8s-secret-namespace
  usage: |
    Kubernetes namespace containing the secret with the auth token
- name: name
  usage: Name of credential (ignored as a kubectl plugin)
inherited_options:
- name: pxc.config
  usage: Config file (default is $HOME/.pxc/config.yml)
- name: pxc.config-dir
  default_value: /home/lpabon/.pxc
  usage: Config directory
- name: pxc.context
  usage: Force context name for the command
- name: pxc.token
  usage: Portworx authentication token
- name: pxc.v
  default_value: "0"
  usage: '[0-3] Log level verbosity'
example: |2-

    # Login to portworx using a secret in Kubernetes
    pxc config credentials set --name=mycreds --k8s-secret-name=abc --k8s-secret-namespace=ns

    # Login to portworx using a specified token
    pxc config credentials set --name=mycreds --auth-token=eyJh...sb30pro
see_also:
- pxc config credentials - Setup pxc authentication
